name: CI-PIPELINE
'on':
  push:
    branches:
      - main
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout_code
        uses: actions/checkout@v5
      - name: Set_up_Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16
      - name: Install-dependencies
        run: npm install
      - name: Run_test
        run: npm test
